apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.application.name }}
    {{- range $key, $value := .Values.application.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.application.name }}
    {{- range $key, $value := .Values.service.selector }}
    {{ $key }}: {{ $value }}
    {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.containerPort }}
