application:
  name: boldx-demo-app
  namespace: default
  labels:
    version: latest


deployment:
  live:
    image:
      repository: "742371491182.dkr.ecr.eu-west-1.amazonaws.com/boldx-demo-app"
      tag: latest
  imagePullPolicy: Always
  portName: http
  containerPort: 8080
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  environment:
    GELF_HOST: "logstash-logstash.monitoring.svc.cluster.local"
    JAEGER_HOST: "jaeger-tracing-collector.monitoring.svc.cluster.local"
service:
  timeout: 30000
  port: 8080
  selector: {}






