logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  logstash.conf: |
    input {
      gelf {
        type => docker
        port => 12201
      }
    }
    output {
      stdout {}
      elasticsearch {
        hosts => ["http://elasticsearch-master.monitoring.svc.cluster.local:9200"]
        data_stream => "true"
      }
    }

service:
  ports:
  - name: gelf
    port: 12201
    protocol: TCP
    targetPort: 12201
