adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

persistence:
  enabled: true

env:
  GF_EXTERNAL_IMAGE_STORAGE_S3_ACCESS_KEY: "AKIA2ZWGJ7VXLFGWZOEJ"
  GF_EXTERNAL_IMAGE_STORAGE_S3_SECRET_KEY: "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"
  GF_EXTERNAL_IMAGE_STORAGE_PROVIDER: s3
  GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET: boldx-grafana-resources
  GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET_URL: https://boldx-grafana-resources.s3-eu-west-1.amazonaws.com/
  GF_EXTERNAL_IMAGE_STORAGE_S3_REGION: eu-west-1

