#
#  ██████╗  ██████╗ ██╗     ██████╗ ██╗███╗   ██╗████████╗
#  ██╔══██╗██╔═══██╗██║     ██╔══██╗██║████╗  ██║╚══██╔══╝
#  ██████╔╝██║   ██║██║     ██║  ██║██║██╔██╗ ██║   ██║
#  ██╔══██╗██║   ██║██║     ██║  ██║██║██║╚██╗██║   ██║
#  ██████╔╝╚██████╔╝███████╗██████╔╝██║██║ ╚████║   ██║
#  ╚═════╝  ╚═════╝ ╚══════╝╚═════╝ ╚═╝╚═╝  ╚═══╝   ╚═╝
#
# Copyright Bold International 2021
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  cdk-version: 1.124.0

jobs:

  deploy:
    name: Deploy - Production
    runs-on: ubuntu-20.04
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v2

      # Python Setup
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Upgrade pip
      - name: Upgrade pip
        run: pip install --upgrade pip

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'

      # CDK Setup
      - name: CDK Setup
        run: npm install -g cdk@${{ env.cdk-version }}

      # Install Requirements
      - name: Install requirements
        run: pip install --user -r requirements.txt

      # CDK Diff
      - name: CDK Diff
        run: |-
          cdk bootstrap
          cdk diff

      # CDK Deploy
      - name: CDK Deploy
        run: cdk deploy --all --require-approval never
